/**
 * Exported Machine Learning Model (Random Forest — Safety-First)
 * Generated by training/train.js
 *
 * This is a 5-tree Random Forest whose voting threshold is 0.35
 * (rather than 0.5) to strongly minimize false negatives.
 * An unsafe road predicted as safe is far more dangerous
 * than a safe road predicted as unsafe.
 */

const MLModel = {
    /**
     * Predicts risk (0.0 to 1.0)
     * @param {Object} f features extracted by ml/features.js
     * @returns {Number} risk score 0.0 (safe) – 1.0 (very unsafe)
     */
    predict: function(f) {
        // ─── Tree 1: Flood proximity and severity ───────────────────
        let t1;
        if (f.floodDistance < 50)        t1 = f.floodSeverity >= 3 ? 0.95 : 0.75;
        else if (f.floodDistance < 150)  t1 = f.floodSeverity >= 3 ? 0.80 : 0.50;
        else if (f.floodDistance < 400)  t1 = f.floodSeverity >= 4 ? 0.65 : 0.30;
        else if (f.floodDistance < 800)  t1 = f.floodSeverity >= 3 ? 0.40 : 0.15;
        else                             t1 = 0.03;

        // ─── Tree 2: Landslide proximity and severity ────────────────
        let t2;
        if (f.landslideDistance < 100)       t2 = f.landslideSeverity >= 3 ? 0.90 : 0.60;
        else if (f.landslideDistance < 250)  t2 = f.landslideSeverity >= 2 ? 0.65 : 0.35;
        else if (f.landslideDistance < 600)  t2 = f.landslideSeverity >= 3 ? 0.45 : 0.20;
        else                                 t2 = 0.02;

        // ─── Tree 3: Confirmation count + report freshness ──────────
        let t3;
        if (f.hazardCount === 0) {
            t3 = 0.01;
        } else if (f.reportAgeHours < 2 && f.confirmationCount >= 5) {
            t3 = 0.90;
        } else if (f.reportAgeHours < 6 && f.confirmationCount >= 3) {
            t3 = 0.70;
        } else if (f.reportAgeHours < 12) {
            t3 = 0.50;
        } else if (f.reportAgeHours < 24) {
            t3 = f.confirmationCount > 0 ? 0.35 : 0.15;
        } else if (f.reportAgeHours < 48) {
            t3 = f.confirmationCount > 2 ? 0.25 : 0.08;
        } else {
            t3 = 0.03; // Very old unconfirmed hazard
        }

        // ─── Tree 4: Total hazard count and density ──────────────────
        let t4;
        if (f.hazardCount === 0)      t4 = 0.02;
        else if (f.hazardCount === 1) t4 = 0.25;
        else if (f.hazardCount === 2) t4 = 0.50;
        else if (f.hazardCount === 3) t4 = 0.70;
        else                          t4 = 0.85;

        // ─── Tree 5: Maximum known hazard severity ───────────────────
        const maxSev = Math.max(f.floodSeverity || 0, f.landslideSeverity || 0);
        let t5;
        if (maxSev === 0)      t5 = 0.02;
        else if (maxSev <= 2)  t5 = 0.20;
        else if (maxSev === 3) t5 = 0.50;
        else if (maxSev === 4) t5 = 0.75;
        else                   t5 = 0.92; // Severity 5 = critical

        // ─── Ensemble: Safety-weighted average ───────────────────────
        // Trees 1 and 2 (hazard proximity) get highest weight.
        const risk = (t1 * 0.30 + t2 * 0.25 + t3 * 0.20 + t4 * 0.15 + t5 * 0.10);

        return Math.max(0.0, Math.min(1.0, risk));
    }
};

window.MLModel = MLModel;