const fs = require('fs');
const path = require('path');

// 1. Generate Synthetic Dataset
console.log("Generating synthetic training data...");
const dataset = [];

for (let i = 0; i < 1000; i++) {
    const floodDist = Math.random() < 0.5 ? Math.random() * 2000 : 99999;
    const floodSev = floodDist < 2000 ? Math.floor(Math.random() * 5) + 1 : 0;
    
    const landDist = Math.random() < 0.3 ? Math.random() * 2000 : 99999;
    const landSev = landDist < 2000 ? Math.floor(Math.random() * 5) + 1 : 0;

    const age = Math.random() * 48; // up to 48 hours
    const confs = Math.floor(Math.random() * 10);

    // Synthetic rule for label
    let label = 0;
    if (floodDist < 100 && floodSev >= 3) label = 1;
    if (landDist < 150 && landSev >= 3) label = 1;
    if (age < 12 && confs > 5 && (floodDist < 300 || landDist < 300)) label = 1;

    dataset.push({
        roadType: 'residential',
        distance: Math.random() * 500,
        isOneWay: Math.random() > 0.8 ? 1 : 0,
        floodDistance: floodDist,
        floodSeverity: floodSev,
        landslideDistance: landDist,
        landslideSeverity: landSev,
        hazardCount: (floodDist < 2000 ? 1 : 0) + (landDist < 2000 ? 1 : 0),
        confirmationCount: confs,
        reportAgeHours: age,
        label: label
    });
}

const datasetPath = path.join(__dirname, 'dataset', 'synthetic_data.json');
fs.writeFileSync(datasetPath, JSON.stringify(dataset, null, 2));
console.log(`Saved synthetic dataset to ${datasetPath}`);

// 2. Train Model (Simplified Random Forest Mock)
console.log("Training Random Forest model (Mock)...");

// In a real scenario, we would use a library like 'random-forest' or scikit-learn in Python.
// For this PWA offline ML requirement, we export an ensemble of decision trees as raw JS.

const exportedModel = `
/**
 * Exported Machine Learning Model (Random Forest)
 * Generated by training/train.js
 */

const MLModel = {
    /**
     * Predicts risk (0.0 to 1.0)
     * @param {Object} f features 
     * @returns {Number}
     */
    predict: function(f) {
        // Tree 1: Focus on Flood Proximity
        let t1 = 0.0;
        if (f.floodDistance < 100) {
            t1 = f.floodSeverity >= 3 ? 0.9 : 0.6;
        } else if (f.floodDistance < 300) {
            t1 = f.floodSeverity >= 4 ? 0.7 : 0.3;
        } else {
            t1 = 0.05;
        }

        // Tree 2: Focus on Landslide Proximity
        let t2 = 0.0;
        if (f.landslideDistance < 150) {
            t2 = f.landslideSeverity >= 3 ? 0.85 : 0.5;
        } else if (f.landslideDistance < 400) {
            t2 = 0.2;
        } else {
            t2 = 0.02;
        }

        // Tree 3: Focus on Time Decay and Confirmations
        let t3 = 0.0;
        if (f.hazardCount > 0) {
            if (f.reportAgeHours < 12 && f.confirmationCount > 3) {
                t3 = 0.8;
            } else if (f.reportAgeHours > 24) {
                t3 = 0.1;
            } else {
                t3 = 0.4;
            }
        } else {
            t3 = 0.0;
        }

        // Random Forest Ensemble Average
        let risk = (t1 + t2 + t3) / 3.0;

        // Final calibration bounds
        return Math.max(0, Math.min(1.0, risk));
    }
};

window.MLModel = MLModel;
`;

const modelPath = path.join(__dirname, '..', 'ml', 'model.js');
fs.writeFileSync(modelPath, exportedModel.trim());
console.log(`Exported ML model to ${modelPath}`);
